# Numpy (Numerical Python)

In [1]:
# Def: Numpy is a open source python library.
# used for Numerical operations.

In [2]:
# import numpy operations:
# 1. Install, upgrade and import numpy
# 2. Creating Numpy arrays
# 3. Specific type of Numpy array
# 4. Array shape & reshape & transpose
# 5. Size & data types of numpy elements
# 6. Indexing & Slicing & Modification
# 7. Mathematical & Statistical operations
# 8. Concatinating arrays

# 1. Install, upgrade and import numpy

In [3]:
# conda install numpy

import numpy as np

In [4]:
np.__version__

'2.1.3'

In [5]:
# pip install -U numpy

# 2. Creating Numpy arrays

In [6]:
# 1D array

break_up = np.array([0, 10, 1, 3, 5, 100, 2, 9, 10, 4])

print(break_up)

[  0  10   1   3   5 100   2   9  10   4]


In [7]:
print(type(break_up))

<class 'numpy.ndarray'>


In [8]:
print(break_up.dtype)

int64


In [9]:
break_up.ndim

1

In [10]:
# Numpy array are Homogeneious

arr2 = np.array([10, 20, 5.7, 9.5, "Kavya"])
print(arr2)

['10' '20' '5.7' '9.5' 'Kavya']


In [11]:
arr2.dtype

dtype('<U32')

In [12]:
# Interview Question: Who is faster:  List or Numpy array?
# Numpy array is faster then List
# Numpy array store the data in continuous memory location 
# while List store the data in NOT continuous memory location

In [20]:
# 2D array
Movie_arr = np.array([["Jaanu", "Salaar", "KGF"],["Sasank dada MBBS", "Eega", "OG"]])

print(Movie_arr)

[['Jaanu' 'Salaar' 'KGF']
 ['Sasank dada MBBS' 'Eega' 'OG']]


In [21]:
print(type(Movie_arr))
print(Movie_arr.dtype)
print(Movie_arr.ndim)
print(Movie_arr.shape)

<class 'numpy.ndarray'>
<U16
2
(2, 3)


In [22]:
study_arr = np.array([[1,2,3], [4,5,6]])
print(study_arr)

[[1 2 3]
 [4 5 6]]


In [29]:
# 3D array
three_D = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(three_D)
print(three_D.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [30]:
print(three_D.shape)

(3, 2, 3)


In [32]:
# 4D array
four_D = np.array([[[[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]], [[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]]]])

In [33]:
print(four_D)

[[[[[1 2 3]
    [4 5 6]]

   [[1 2 3]
    [4 5 6]]]


  [[[1 2 3]
    [4 5 6]]

   [[1 2 3]
    [4 5 6]]]]]


In [34]:
print(four_D.shape)

(1, 2, 2, 2, 3)


# 3. Specific type of Numpy array

In [1]:
import numpy as np

In [2]:
# zeros() numpy function create an 1D array initialize with zeros.
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [4]:
arr = np.zeros(10)
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
# 2D Zero array
arr_2d = np.zeros((2,4))
print(arr_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 3D Zero array
arr_3d = np.zeros((2,3,4))
print(arr_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
# np.ones() : array initialize with ones
ones_1d = np.ones(6)
print(ones_1d)

[1. 1. 1. 1. 1. 1.]


In [9]:
# np.ones() : array initialize with ones
ones_2d = np.ones((2,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# np.ones() : array initialize with ones
ones_3d = np.ones((2,4,3))
print(ones_3d)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
# np.full() : fill the array with any number

arr_full = np.full(10, 500)
print(arr_full)

[500 500 500 500 500 500 500 500 500 500]


In [23]:
arr_full = np.full((3,2,4), 14)
print(arr_full)

[[[14 14 14 14]
  [14 14 14 14]]

 [[14 14 14 14]
  [14 14 14 14]]

 [[14 14 14 14]
  [14 14 14 14]]]


In [27]:
# identity matrix : all diagnol elements are 1.
# identity matrix is a Squared matrix
id_arr = np.eye(5)
print(id_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
# numpy random package

# rand() : random values between 0 and 1

np.random.rand(10)  

array([0.0091644 , 0.67149012, 0.17501264, 0.22309881, 0.09562373,
       0.69541805, 0.55200436, 0.0553421 , 0.81544578, 0.29795451])

In [32]:
# 2D random array
np.random.rand(2,4,2)

array([[[0.38265376, 0.78070366],
        [0.48042114, 0.29032503],
        [0.70373997, 0.3205531 ],
        [0.10767641, 0.77545351]],

       [[0.33207176, 0.29944463],
        [0.99627957, 0.3951264 ],
        [0.39784937, 0.37824503],
        [0.71962275, 0.75619898]]])

In [35]:
# uniform distribution: every value have equal chance to get selected
np.random.uniform(low = 1, high = 15, size = (2,3,4))

array([[[ 4.96553277,  9.35706757, 13.84359181, 12.60697146],
        [ 4.77735355,  1.5208002 , 12.13969252,  1.9192149 ],
        [ 9.27679488, 12.26905341,  9.68642055, 12.24440453]],

       [[11.23630416, 13.71731276, 11.12392857,  6.6186283 ],
        [ 6.29526067,  3.79310351,  8.96036221, 10.09181959],
        [ 8.72884671,  4.56278865,  5.16201096,  6.51367376]]])

In [39]:
# here n means Normal distribution : most of the values are between -3 to +3
np.random.randn(4)

array([-0.59510821, -0.85505196, -1.15930116, -0.36778376])

In [40]:
# create a 2D array which is having normal distributed data

np.random.randn(3,4)

array([[-1.68175197,  0.38147707, -1.29967166,  0.8004715 ],
       [-0.25896123,  0.78171068, -2.03896148,  0.2289356 ],
       [ 0.40877277,  1.34369052, -1.75130995,  0.04508882]])

In [43]:
np.random.randint(50, 70, (2,3))

array([[51, 51, 54],
       [64, 66, 58]], dtype=int32)

In [55]:
np.random.seed(32)
x_names = np.array(["Sruthi", "Kavya", "Murgi", "Bakri", "Chuhiya"])

np.random.choice(x_names, size = 3, replace = False)

array(['Chuhiya', 'Sruthi', 'Murgi'], dtype='<U7')

In [53]:
np.random.choice(x_names, size = 30, p = [0.1, 0.50, 0.2,0.1,0.1] )

array(['Kavya', 'Kavya', 'Kavya', 'Kavya', 'Kavya', 'Kavya', 'Murgi',
       'Kavya', 'Bakri', 'Kavya', 'Kavya', 'Sruthi', 'Kavya', 'Murgi',
       'Murgi', 'Kavya', 'Kavya', 'Kavya', 'Chuhiya', 'Bakri', 'Kavya',
       'Sruthi', 'Kavya', 'Kavya', 'Chuhiya', 'Kavya', 'Kavya', 'Kavya',
       'Kavya', 'Kavya'], dtype='<U7')